name: Otomasi Scraping & Update WebGIS Karhutla

on:
  schedule:
    # 01:00 WIB = 18:00 UTC (H-1). Cron UTC: Menit Jam * * *
    # Berjalan tiap 3 jam: 18:00, 21:00, 00:00, 03:00, 06:00, 09:00, 12:00, 15:00 UTC
    - cron: '0 18,21,0,3,6,9,12,15 * * *'
  workflow_dispatch: # Memungkinkan tombol 'Run Workflow' manual

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies (GDAL/GEOS)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin libgeos-dev

      - name: Install Python Libraries
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas geopandas folium shapely urllib3

      - name: Jalankan Script Main.py
        run: python assets/main.py

      - name: Commit & Push Output Terbaru ke GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ stats.json peta.html
          git commit -m "Auto-update data hotspot [$(date +'%Y-%m-%d %H:%M WIB')]" || exit 0
          git push
